server:
  port: 9090

spring:
  data:
    mongodb:
      host: localhost
      port: 27027
      database: AdminLoginDB
      username: admin
      password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

authservice:
  secret:
    secret-key: ${SIS_SECRET_KEY}
    issuer: ${SIS_ISSUER}



springdoc:
  swagger-ui:
    tryItOutEnabled: false

