server:
  port: 9093

spring:
  data:
    mongodb:
      host: localhost
      port: 27027
      database: CartDB
      username: sisburger
      password: root

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password


cartservice:
  secret:
    secret-key: "OktUenBm7lbgzQ2"
    secret-issuer: "sisburger"
  redis:
    host: localhost
    port: 6379

