server:
  port: 80

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - RewritePath=/(?<segment>.*), /api/v1/$\{segment}
      routes:
        - id: admin-service
          uri: http://localhost:9090
          predicates:
            - Path=/admin/**
          filters:
            - name: CircuitBreaker
              args:
                name: adminCircuitBreaker
                fallbackUri: forward:/fallback/auth
        - id: user-service
          uri: http://localhost:9092
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: userCircuitBreaker
                fallbackUri: forward:/fallback/user
        - id: product-service
          uri: http://localhost:9091
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: productCircuitBreaker
                fallbackUri: forward:/fallback/product

        - id: cart-service
          uri: http://localhost:9093
          predicates:
            - Path=/cart/**
          filters:
            - name: CircuitBreaker
              args:
                name: cartCircuitBreaker
                fallbackUri: forward:/fallback/cart