server:
  port: 9090

spring:
  data:
    mongodb:
      host: localhost
      port: 27027
      database: AdminDB
      username: sisburger
      password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

adminservice:
  secret:
    secret-key: ${SIS_SECRET_KEY}
    issuer: ${SIS_ISSUER}
    admin-name: "admin"
    admin-password: "root"





