server:
  port: 9090

spring:
  data:
    mongodb:
      host: localhost
      port: 27027
      database: AdminHomeDB
      username: sisburger
      password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

adminservice:
  secret:
    secret-key: "OktUenBm7lbgzQ2"
    secret-issuer: "sisburger"
    admin-name: "admin"
    admin-password: "root"





